#!/usr/bin/env bash
# cli-install.sh                   build the command-line tools and stage them
# cli-install.sh --print-bin-dir   print where they are staged, and exit
#
# Builds the multi-call binary in release mode (`--features cli`, which the
# target requires) and stages it in tmp/cli/bin under every name it answers
# to: `rust-img-vmdk`, the real file, and each dotted name as a relative
# symlink to it -- the layout an install has. The dotted names come from the
# binary itself (`rust-img-vmdk generate names`), so this script names none.
# The man pages and completions go in tmp/cli/share, beside bin/, where an
# install puts them, and are generated by the binary too.
#
# It prints the PATH line to use. `chore test:cli` tests whatever PATH
# finds, so the staged directory has to come first for it to test these.
#
# CLI_INSTALL_DIR names another prefix (the binary goes in its bin/).
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)"
PREFIX="${CLI_INSTALL_DIR:-$REPO/tmp/cli}"
BIN="$PREFIX/bin"

if [ "${1:-}" = "--print-bin-dir" ]; then
    printf '%s\n' "$BIN"
    exit 0
fi

cd "$REPO"
cargo build --locked --release --features cli --bin rust-img-vmdk --quiet
built="${CARGO_TARGET_DIR:-$REPO/target}/release/rust-img-vmdk"
[ -x "$built" ] || { echo "cli-install: cargo built no $built" >&2; exit 1; }

SHARE="$PREFIX/share"
rm -rf "$BIN" "$SHARE"
mkdir -p "$BIN" "$SHARE"
cp "$built" "$BIN/rust-img-vmdk"
names="$("$BIN/rust-img-vmdk" generate names)"
[ -n "$names" ] || { echo "cli-install: the binary lists no tool names" >&2; exit 1; }
for name in $names; do
    ln -s rust-img-vmdk "$BIN/$name"
done

"$BIN/rust-img-vmdk" generate man "$SHARE" >/dev/null
"$BIN/rust-img-vmdk" generate completions "$SHARE" >/dev/null

echo "cli:install: staged rust-img-vmdk and $(echo $names | tr ' ' ',') in $BIN"
echo "cli:install: to test or use them, put that directory first on PATH:"
echo "  export PATH=\"$BIN:\$PATH\""
